#!/usr/bin/env bash
set -e
subdeck=$(echo "$1" | sed 's,/*$,,')
remote=$2
root=$(git rev-parse --show-toplevel)

rm -rf /tmp/ki
mkdir -p /tmp/ki
cd /tmp/ki
git clone $root $subdeck
cd $subdeck
git subtree split --prefix $subdeck
cd $(git rev-parse --show-toplevel)
git remote rm origin
git remote add origin $remote
git push -u origin main

echo "commits for deck '$subdeck' pushed to '$remote'"
